# -*- coding: utf-8 -*-
"""Codigos_aula2_visao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ya_OZfFsAU9Cx0caGUuubn3J6ZYfgbH

Exemplo para plotar gráfico
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import numpy as np

## plota os gráficos em novas janelas
#%matplotlib qt

## plota os gráficos dentro da célula
# %matplotlib inline

def f(t):
    return np.exp(-t) * np.cos(2*np.pi*t)

# Definindo valores no vetor t1 e t2
t1 = np.arange(0.0, 5.0, 0.1)
t2 = np.arange(0.0, 5.0, 0.02)

plt.figure(1)
plt.subplot(211)
plt.plot(t1, f(t1), 'bo', t2, f(t2), 'k')

plt.subplot(212)
plt.plot(t2, np.cos(2*np.pi*t2), 'r--')
plt.show()

#Abrindo uma imagem

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import urllib.request

# URL da imagem
url = 'https://matplotlib.org/3.3.3/_images/stinkbug.png'

# Abrir a URL e ler a imagem
with urllib.request.urlopen(url) as url_response:
    image = np.array(Image.open(url_response))

# Exibir a imagem
plt.imshow(image)
plt.axis('off')  # Ocultar os eixos
plt.show()

"""Estrutura de uma imagem"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline


import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2

img = mpimg.imread('https://matplotlib.org/3.3.3/_images/stinkbug.png')
print(img)
imgplot = plt.imshow(img)

"""Abrindo uma imagem na escala de cinza"""

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import urllib.request
import cv2

# URL da imagem
url = 'https://matplotlib.org/3.3.3/_images/stinkbug.png'

# Abrir a URL e ler a imagem
with urllib.request.urlopen(url) as url_response:
    image = np.array(Image.open(url_response))

# Converter a imagem de RGB (Pillow) para BGR (OpenCV)
image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Exibir a imagem usando matplotlib (que espera a imagem em RGB)
plt.imshow(cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB))
plt.axis('off')  # Ocultar os eixos
plt.show()

"""Convertendo uma imagem em HSV"""

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import urllib.request
import cv2

# URL da imagem
url = 'https://matplotlib.org/3.3.3/_images/stinkbug.png'

# Abrir a URL e ler a imagem
with urllib.request.urlopen(url) as url_response:
    image = np.array(Image.open(url_response))

# Converter a imagem de RGB (Pillow) para BGR (OpenCV)
image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Converter a imagem de BGR para HSV
image_hsv = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2HSV)

# Exibir a imagem HSV usando matplotlib
plt.imshow(image_hsv)
plt.axis('off')  # Ocultar os eixos
plt.show()

"""Mapeando em HSV"""

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import urllib.request
import cv2

# URL da imagem
url = 'https://matplotlib.org/3.3.3/_images/stinkbug.png'

# Abrir a URL e ler a imagem
with urllib.request.urlopen(url) as url_response:
    image = np.array(Image.open(url_response))

# Converter a imagem de RGB (Pillow) para BGR (OpenCV)
image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Converter a imagem de BGR para HSV
image_hsv = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2HSV)

# Mapear e exibir os canais HSV separadamente
hue, saturation, value = cv2.split(image_hsv)

# Exibir o canal Hue
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.title('Hue Channel')
plt.imshow(hue, cmap='hsv')
plt.axis('off')

# Exibir o canal Saturation
plt.subplot(1, 3, 2)
plt.title('Saturation Channel')
plt.imshow(saturation, cmap='gray')
plt.axis('off')

# Exibir o canal Value
plt.subplot(1, 3, 3)
plt.title('Value Channel')
plt.imshow(value, cmap='gray')
plt.axis('off')

plt.show()

"""Abrindo uma imagem no plano de cinza"""

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import urllib.request
import cv2

# URL da imagem
url = 'https://matplotlib.org/3.3.3/_images/stinkbug.png'

# Abrir a URL e ler a imagem
with urllib.request.urlopen(url) as url_response:
    image = np.array(Image.open(url_response))

# Converter a imagem de RGB (Pillow) para BGR (OpenCV)
image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Converter a imagem de BGR para Grayscale
image_gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

# Exibir a imagem em Grayscale usando matplotlib
plt.imshow(image_gray, cmap='gray')
plt.axis('off')  # Ocultar os eixos
plt.title('Grayscale Image')
plt.show()

"""Redimensionando uma imagem"""

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import urllib.request
import cv2

# URL da imagem
url = 'https://matplotlib.org/3.3.3/_images/stinkbug.png'

# Abrir a URL e ler a imagem
with urllib.request.urlopen(url) as url_response:
    image = np.array(Image.open(url_response))

# Converter a imagem de RGB (Pillow) para BGR (OpenCV)
image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Definir novas dimensões (por exemplo, 200x200 pixels)
new_width = 200
new_height = 200

# Redimensionar a imagem
resized_image = cv2.resize(image_bgr, (new_width, new_height))

# Converter a imagem redimensionada de BGR para RGB para exibição
resized_image_rgb = cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB)

# Exibir a imagem redimensionada
plt.imshow(resized_image_rgb)
plt.axis('off')  # Ocultar os eixos
plt.title('Resized Image')
plt.show()

"""Aplicando Affine Transform"""

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import urllib.request
import cv2

# URL da imagem
url = 'https://matplotlib.org/3.3.3/_images/stinkbug.png'

# Abrir a URL e ler a imagem
with urllib.request.urlopen(url) as url_response:
    image = np.array(Image.open(url_response))

# Converter a imagem de RGB (Pillow) para BGR (OpenCV)
image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Dimensões da imagem
rows, cols, ch = image_bgr.shape

# Definir pontos para a transformação afim
pts1 = np.float32([[50, 50], [200, 50], [50, 200]])
pts2 = np.float32([[10, 100], [200, 50], [100, 250]])

# Calcular a matriz de transformação afim
M = cv2.getAffineTransform(pts1, pts2)

# Aplicar a transformação afim
affine_transformed_image = cv2.warpAffine(image_bgr, M, (cols, rows))

# Converter a imagem transformada de BGR para RGB para exibição
affine_transformed_image_rgb = cv2.cvtColor(affine_transformed_image, cv2.COLOR_BGR2RGB)

# Exibir a imagem original e a transformada lado a lado
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.title('Original Image')
plt.imshow(cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1, 2, 2)
plt.title('Affine Transformed Image')
plt.imshow(affine_transformed_image_rgb)
plt.axis('off')

plt.show()

"""Aplicando Edge Detector"""

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import urllib.request
import cv2

# URL da imagem
url = 'https://matplotlib.org/3.3.3/_images/stinkbug.png'

# Abrir a URL e ler a imagem
with urllib.request.urlopen(url) as url_response:
    image = np.array(Image.open(url_response))

# Converter a imagem de RGB (Pillow) para BGR (OpenCV)
image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Converter a imagem para escala de cinza (necessário para a detecção de bordas)
image_gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

# Aplicar o detector de bordas de Canny
edges = cv2.Canny(image_gray, threshold1=100, threshold2=200)

# Exibir a imagem original e a imagem com detecção de bordas lado a lado
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.title('Original Image')
plt.imshow(cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1, 2, 2)
plt.title('Edge Detection')
plt.imshow(edges, cmap='gray')
plt.axis('off')

plt.show()

#pip install opencv-contrib-python

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import urllib.request
import cv2

# Verificar se SIFT está disponível
if cv2.__version__.startswith('4'):
    sift = cv2.SIFT_create()
else:
    sift = cv2.xfeatures2d.SIFT_create()

# URL da imagem
url = 'https://matplotlib.org/3.3.3/_images/stinkbug.png'

# Abrir a URL e ler a imagem
with urllib.request.urlopen(url) as url_response:
    image = np.array(Image.open(url_response))

# Converter a imagem de RGB (Pillow) para BGR (OpenCV)
image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Converter a imagem para escala de cinza (necessário para o SIFT)
image_gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

# Detectar keypoints e calcular descritores
keypoints, descriptors = sift.detectAndCompute(image_gray, None)

# Desenhar keypoints na imagem
image_with_keypoints = cv2.drawKeypoints(image_bgr, keypoints, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

# Converter a imagem de BGR para RGB para exibição
image_with_keypoints_rgb = cv2.cvtColor(image_with_keypoints, cv2.COLOR_BGR2RGB)

# Exibir a imagem original e a imagem com keypoints lado a lado
plt.figure(figsize=(15, 5))

plt.subplot(1, 2, 1)
plt.title('Original Image')
plt.imshow(cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1, 2, 2)
plt.title('Image with SIFT Keypoints')
plt.imshow(image_with_keypoints_rgb)
plt.axis('off')

plt.show()